---

- name: Zip de {{origem}}
  hosts: all
  tasks:
    - name: zipa arquivos {{origem}}
      ansible.windows.win_shell: |
        $atual = Get-Date -Format "dd/MM/yyyy-HHmmss"
        $destino_final="{{destino}}\LOG_$atual.zip"
        Compress-Archive -Path '{{origem}}'  -DestinationPath $destino_final

...