---

- name: Zip de {{origem}}
  hosts: all
  gather_facts: False
  tasks:
    - name: zipa arquivos {{origem}}
      ansible.windows.win_shell: |
        $atual = Get-Date -Format "ddMMyyyy_HHmmss"
        $destino_final="{{destino}}\LOG_$atual.zip"
        Compress-Archive -Path '{{origem}}'  -DestinationPath $destino_final

...