---

- name: Copy temp > documents
  hosts: all
  tasks:
    - name: COPY  FILE | temp > documents
      ansible.builtin.win_copy:
        src: c:\temp\teste.txt
        #src: C:\temp\"{{ ansible_facts['date_time']['date'] }}".log
        #dest: \\LAPTOP-1A49H3L2\Users\Public\Documents\bkp\"{{ ansible_facts['date_time']['date'] }}".log
        dest: c:\temp\
        remote_src: true
...



