---

- name: Install packages
  hosts: all
  tasks:
    - name: YUM | Install packages
      yum: name={{ packages }} state=latest
      when: ansible_distribution == "Rocky" or  ansible_distribution_file_variety == "RedHat"
...
