---

- name: Zip de Logs
  hosts: windows01
  tasks:
    - name: Zipando logs da pasta temp
      community.windows.win_zip:
        src: c:\temp\*
        dest: c:\file.zip

    - name: Remove a file, if present
      ansible.windows.win_file:
        path: C:\Temp\
        state: absent

...