---

- name: Expurgo {{caminho}}
  hosts: all
  gather_facts: False
  tasks:
    - name: Realizando o Expurgo do {{caminho}}
      ansible.windows.win_shell: |
        Remove-Item -Path '{{caminho}}'


...