---
- name: substituir string
  hosts: all
  gather_facts: False
  tasks:
    - name: replace in arquivo
      shell: cd "{{local}}" && sed -i 's/"{{string_procurada}}"/"{{string_substituta}}"/' "{{arquivo}}"

...
