---
- name: Replace text in a file
  hosts: all
  gather_facts: False
  tasks:
    - name: Replace text
      replace:
        path: "{{local}}"
        regexp: "{{string_procurada}}"
        replace: "{{string_substituta}}"
...
