---

- name: Copia de arquivos
  hosts: all
  gather_facts: False
  tasks:
    - name: Realizando a Copia do Arquivo 
      ansible.windows.win_shell: |
        Copy-Item '{{origem}}' -Destination '{{destino}}' 

        
...

